const fs = require("fs");
const path = require("path");

async function main() {
  console.log("📦 Exporting network configuration...\n");
  
  // Read deployment files
  const deploymentsDir = path.join(__dirname, "..", "deployments");
  
  if (!fs.existsSync(deploymentsDir)) {
    console.log("⚠️  No deployments found. Deploy contracts first.");
    return;
  }
  
  const localhostFile = path.join(deploymentsDir, "localhost.json");
  const cloudFile = path.join(deploymentsDir, "cloud.json");
  
  let localhostDeployment = null;
  let cloudDeployment = null;
  
  if (fs.existsSync(localhostFile)) {
    localhostDeployment = JSON.parse(fs.readFileSync(localhostFile, "utf8"));
    console.log("✅ Found localhost deployment");
  }
  
  if (fs.existsSync(cloudFile)) {
    cloudDeployment = JSON.parse(fs.readFileSync(cloudFile, "utf8"));
    console.log("✅ Found cloud deployment");
  }
  
  // Read ABI
  const abiFile = path.join(deploymentsDir, "POAToken-abi.json");
  let abi = null;
  
  if (fs.existsSync(abiFile)) {
    abi = JSON.parse(fs.readFileSync(abiFile, "utf8"));
    console.log("✅ Found POAToken ABI");
  }
  
  // Create index.js with exports
  const indexContent = `// Proof-of-Art Network - Configuration Exports
// This file is auto-generated by 'npm run export:config'

const networkConfig = {
  id: 31337,
  name: "Proof-of-Art Network",
  network: "proof-of-art",
  nativeCurrency: {
    name: "Ethereum",
    symbol: "ETH",
    decimals: 18
  },
  rpcUrls: {
    default: {
      http: ["http://127.0.0.1:8545"]
    },
    public: {
      http: ["http://127.0.0.1:8545"]
    }
  },
  blockExplorers: {
    default: {
      name: "Local Explorer",
      url: "http://127.0.0.1:8545"
    }
  },
  testnet: true
};

// Deployment addresses
const deployments = ${JSON.stringify(
  {
    localhost: localhostDeployment ? localhostDeployment.address : null,
    cloud: cloudDeployment ? cloudDeployment.address : null
  },
  null,
  2
)};

// POA Token ABI
const poaTokenABI = ${abi ? JSON.stringify(abi, null, 2) : "null"};

// RPC URLs
const localRPCUrl = "http://127.0.0.1:8545";
const cloudRPCUrl = process.env.CLOUD_RPC_URL || "https://your-domain.com:8545";

// Main exports
module.exports = {
  networkConfig,
  poaTokenAddress: deployments.localhost || deployments.cloud,
  poaTokenAddresses: deployments,
  poaTokenABI,
  localRPCUrl,
  cloudRPCUrl,
  
  // Helper functions
  getNetworkConfig: () => networkConfig,
  getPOATokenAddress: (network = "localhost") => deployments[network],
  getPOATokenABI: () => poaTokenABI,
  getRPCUrl: (network = "localhost") => network === "cloud" ? cloudRPCUrl : localRPCUrl
};
`;
  
  // Write index.js
  const indexFile = path.join(__dirname, "..", "index.js");
  fs.writeFileSync(indexFile, indexContent);
  console.log("\n✅ Exported configuration to index.js");
  
  console.log("\n📝 Configuration exported successfully!");
  console.log("\nYou can now import in other projects:");
  console.log('  const { networkConfig, poaTokenAddress, poaTokenABI } = require("proof-of-art-network");');
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });

